### ISSUE TITLE
`parity-scale-codec/derive` enables `serder/std` even when `std` is not enabled

### ISSUE THREAD

**Issue by Recmo** [paritytech/parity-scale-codec#204]
Simplified example:

```toml
serde = { version = "1.0", default_features = false }
parity-scale-codec = { version = '1.3.0', default-features = false, features = ['derive'] }

[features]
default = ["std"]
std = [
    "serde/std",
    "parity-scale-codec/std",
]
```

Fails to build correctly without the `std` feature.

This is because `parity-scale-codec` will force the `serde/std` feature to be set, even when `parity-scale-codec/std` is unset.
