### ISSUE TITLE
Building `parity-scale-codec` with `derive` feature still uses `std`

### ISSUE THREAD

**Issue by garrettmaring** [paritytech/parity-scale-codec#285]
When compiling `scale` with the `derive` feature, usage with other packages that use `std` fails.

```toml
[package]
name = "contract"
version = "0.1.0"
edition = "2018"

[profile.dev]
opt-level = 1
overflow-checks = false

[dependencies]
ink_primitives = { version = "3.0.0-rc4", default-features = false }
ink_metadata = { version = "3.0.0-rc4", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc4", default-features = false }
ink_storage = { version = "3.0.0-rc4", default-features = false }
ink_lang = { version = "3.0.0-rc4", default-features = false }
ink_prelude = { version = "3.0.0-rc4", default-features = false }
sp-std = { version = "3.0.0-rc4", default-features = false }
scale = { package = "parity-scale-codec", version = "2.2", features = ["derive"], default-features = false, optional = true }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"], optional = true }
uuid = { version = "0.8", features = ["serde", "v4"], default-features = false, optional = true }

[dev-dependencies]
serde_json = "1.0"
sp-keyring = "3.0.0"

[lib]
name = "contract"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib"
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std"
]
ink-as-dependency = []
```

![Screen Shot 2021-08-07 at 11 56 32 AM](https://user-images.githubusercontent.com/8270120/128611166-74d09673-27d7-4ae1-83ce-e46d3e06825d.png)
